export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const INCREMENT_SECOND = 'INCREMENT_SECOND';
export const RESET_STOPWATCH = 'RESET_STOPWATCH';
export const UPDATE_STOPWATCH = 'UPDATE_STOPWATCH';
