export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const INCREMENT_SECOND = 'INCREMENT_SECOND';
export const INCREMENT_SECOND_BY_PROJECTID = 'INCREMENT_SECOND_BY_PROJECTID';
export const RESET_STOPWATCH_BY_PROJECTID = 'RESET_STOPWATCH';
export const UPDATE_STOPWATCH_BY_PROJECTID = 'UPDATE_STOPWATCH_BY_PROJECTID';
